import "@/styles/globals.css";
import { Ubuntu } from "next/font/google";
import { TRPCReactProvider } from "@/trpc/react";

const inter = Ubuntu({
  subsets: ["latin"],
  variable: "--font-Ubuntu",
  weight: "400",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`font-sans ${inter.variable}`}>
        <TRPCReactProvider>{children}</TRPCReactProvider>
      </body>
    </html>
  );
}
